### ISSUE TITLE
EPIC: set up working environment

### ISSUE THREAD

**Issue by yannickferenczi** [yannickferenczi/hands-home-helpers#1]
As a **Stakeholder**, I can **open a workspace and save my work in the cloud** so that **I can keep working on it at any time from anywhere and my work is safe**.

---
ACCEPTANCE CRITERIA
- [x] A public GitHub repo of the project has been created
- [x] A public GitHub project manager has been created
- [x] A workspace on a Cloud IDE has been created
- [x] A Django project has been set up

---
TASKS
- [x] #2 
- [x] #3 
- [x] #4 
- [x] #6
