### ISSUE TITLE
EPIC: fulfill the UX Design section of the README

### ISSUE THREAD

**Issue by yannickferenczi** [yannickferenczi/hands-home-helpers#35]
As a **Stakeholder of the project**, I can **read the UX Design section of the README file** so that **I have useful information to work on the project**.

---
ACCEPTANCE CRITERIA
- [x] The README file contains a UX Design section
- [x] The UX Design section contains a Strategy Plane subsection
- [x] The UX Design section contains a Scope Plane subsection
- [x] The UX Design section contains a Structure Plane subsection
- [x] The UX Design section contains a Skeleton Plane subsection
- [x] The UX Design section contains a Surface Plane subsection

---
TASKS
- [x] #36 
- [x] #37 
- [x] #38 
- [x] #39 
- [x] #40
