### ISSUE TITLE
EPIC: implement account system

### ISSUE THREAD

**Issue by yannickferenczi** [yannickferenczi/hands-home-helpers#45]
As a **Site user**, I can **create a personal account** so that **I can use the website with personal settings and information**.

---
ACCEPTANCE CRITERIA
- [x] users can register
- [x] users can log in
- [ ] users can modify their information within their personal account
- [x] users can find their personal account back like it was after logging out and signing back in

---
TASKS
- [x] #48 
- [x] #49 
- [x] #50
