### ISSUE TITLE
EPIC: create the common part to all pages

### ISSUE THREAD

**Issue by yannickferenczi** [yannickferenczi/hands-home-helpers#46]
As a **Stakeholder**, I can **reuse the basic design while developing new features** so that **I can be more efficient and be sure that all the common part will be the same on all pages**.

---
ACCEPTANCE CRITERIA
- [ ] a base.html has been created and can be used to implement new pages
- [ ] the base.html has been styled along with the ux design plane

---
TASKS
- [ ] create a base.html file
- [ ] implement the html, css and javascript

**Comment by yannickferenczi** [comment]
- [ ] Need to fix alignment of logo img and logo header
- [ ] Need to fix hamburger menu (it displays the menu but does not close it)
