### ISSUE TITLE
EPIC: implement tasks management system

### ISSUE THREAD

**Issue by yannickferenczi** [yannickferenczi/hands-home-helpers#47]
As a **Site user**, I can **use a tasks management system** so that **I can manage my tasks**.

---
ACCEPTANCE CRITERIA
- [ ] A task can be created
- [ ] A list of tasks can be displayed
- [ ] Details of a task can be displayed
- [ ] A task can be updated
- [ ] A task can be deleted

---
TASKS
- [ ] Create the tasks listing view
- [ ] Create the task detail view
- [ ] Create
