### ISSUE TITLE
EPIC: define the strategy plane

### ISSUE THREAD

**Issue by yannickferenczi** [yannickferenczi/hands-home-helpers#8]
As a **Stakeholder**, I can **read the strategy plane of the project** so that **I know the direction we want to develop the project**.

---
ACCEPTANCE CRITERIA
- [x] Goals and objectives have been clearly defined
- [x] A user research has been ran
- [x] The target audience is clear and at least one customer persona has been created
- [ ] User stories for the minimum viable product have been written

---
TASKS
- [x] #9 
- [x] #10 
- [x] #11 
- [x] #12 
- [x] #13
